### PR TITLE
Formula for Grafana

### PR DESCRIPTION
**Pull request by mateiw**
Formula for configuring Grafana.

Screen Shot 2019-10-30 at 12 32 03

**Note:** depends on enhancements from https://github.com/uyuni-project/uyuni/pull/1527.

### CODE REVIEW

**Comment by uyuni-leader** [comment]
The "Use Prometheus from this minion" option is a shortcut to automatically fill in the datasource? What if we just set that as a default and let the user change it?

"Add Uyuni dashboards" - This means provisioning Grafana with the Uyuni server dashboard, right?

**Comment by cavalheiro** [comment]
The "Use Prometheus from this minion" option is a shortcut to automatically fill in the datasource? What if we just set that as a default and let the user change it?

"Add Uyuni dashboards" - This means provisioning Grafana with the Uyuni server dashboard, right?

**Comment by cavalheiro** [comment]
We might also want to add a checkbox to provision a default "node exporter" dashboard together with the Uyuni server dashboard.

**Comment by cavalheiro** [comment]
When disabling Grafana (inside the formula settings), it is not possible to save the settings if admin user and password are not set, although the fields are not editable in that case. Error: "Please input required fields: Default admin user, Default admin password"

**Comment by cavalheiro** [comment]
Grafana username and password are not being correctly set in grafana.ini - values show as 'None' / 'None'

**Comment by mateiw** [comment]
@cavalheiro I've fixe the issue with the user and pass and I've added the Apache dashboard.

**Pull request merged**
